name: CI

on:
  push:
    branches: [ "main", "feat/**", "fix/**", "chore/**" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  basic-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install uvicorn[standard] fastapi jinja2 sqlalchemy
          pip install pytest coverage httpx

      - name: Quick import test
        run: |
          python - << 'PY'
          import importlib
          for m in ["app", "app.main"]:
              importlib.import_module(m)
          print("imports ok")
          PY
      - name: Run tests with coverage
        run: |
          coverage run -m pytest -q
          coverage xml
          python - << 'PY'
import xml.etree.ElementTree as ET
p = "coverage.xml"
try:
    t = ET.parse(p).getroot()
    rate = float(t.attrib.get("line-rate", "0")) * 100
    print(f"Line coverage: {rate:.2f}%")
except Exception as e:
    print("Coverage parse failed:", e)
PY


      - name: Ruff lint (non-blocking)
        run: ruff --version || true

      - name: Mypy type-check (non-blocking)
        run: mypy --version || true
