name: CI

on:
  push:
  pull_request:

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps (ignore errors if none)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
      - name: Quick import test
        run: |
          python -c "print('ok')"
