name: basic-checks

on:
  pull_request:
    branches: [ main ]

jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      PYTHONPATH: ${{ github.workspace }}
      DB_PATH: ./data/verify_upgrade.db

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn "sqlalchemy>=2" httpx pytest python-dotenv jinja2

      - name: Prepare env
        run: |
          echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "DB_PATH=./data/verify_upgrade.db" >> $GITHUB_ENV
          mkdir -p app/data

      - name: Quick import test
        run: |
          python - <<'PY'
          import importlib
          for m in ['app','app.main']:
              importlib.import_module(m)
          print('imports ok')
          PY

      - name: Run tests
        run: pytest -q
